/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestcolis;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author kamke
 */
public final class colismain extends javax.swing.JFrame {
    
    public static Connection con, cone; 
    public static Statement st, ste;
    public static PreparedStatement ps, pse;
    public static ResultSet rs, rse;                   //permettent d'utiliser les crud
    public static  String ve="",vi="",vp="",vu="",vpw="";

    static void enregistrer(String mat, String nomcolis, String type, String poids, String nomexpediteur, String prenomexpediteur, String telephoneexpediteur, String Villeexpediteur, String nomdestinataire, String prenomdestinataire, String telephonedestinataire, String villedestinataire, String quartierdestinataire, String de, String fraisenvoi, String codeenvoi) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form colismain
     */
    public colismain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seconnecter = new javax.swing.JButton();
        expedition = new javax.swing.JLabel();
        statistiques = new javax.swing.JLabel();
        reception = new javax.swing.JLabel();
        chiffreAffaires = new javax.swing.JLabel();
        personnel = new javax.swing.JLabel();
        panebureau = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        seconnecter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        seconnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_32.png"))); // NOI18N
        seconnecter.setText("Se connecter");
        seconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seconnecterActionPerformed(evt);
            }
        });

        expedition.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        expedition.setForeground(new java.awt.Color(255, 255, 255));
        expedition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/validerfrais_32.png"))); // NOI18N
        expedition.setText("Expédition");
        expedition.setEnabled(false);
        expedition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expeditionMouseClicked(evt);
            }
        });

        statistiques.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        statistiques.setForeground(new java.awt.Color(255, 255, 255));
        statistiques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/statistique_32.png"))); // NOI18N
        statistiques.setText("Statistiques");
        statistiques.setEnabled(false);
        statistiques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statistiquesMouseClicked(evt);
            }
        });

        reception.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reception.setForeground(new java.awt.Color(255, 255, 255));
        reception.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chargerfiliere_32.png"))); // NOI18N
        reception.setText("Réception");
        reception.setEnabled(false);
        reception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receptionMouseClicked(evt);
            }
        });

        chiffreAffaires.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        chiffreAffaires.setForeground(new java.awt.Color(255, 255, 255));
        chiffreAffaires.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chiffresaffaires_32.png"))); // NOI18N
        chiffreAffaires.setText("Chiffre d'affaires");
        chiffreAffaires.setEnabled(false);
        chiffreAffaires.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chiffreAffairesMouseClicked(evt);
            }
        });

        personnel.setBackground(new java.awt.Color(255, 255, 255));
        personnel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        personnel.setForeground(new java.awt.Color(255, 255, 255));
        personnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/administration_32.png"))); // NOI18N
        personnel.setText("Personnel");
        personnel.setEnabled(false);
        personnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personnelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statistiques)
                    .addComponent(expedition, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reception, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chiffreAffaires)
                    .addComponent(seconnecter)
                    .addComponent(personnel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(expedition)
                .addGap(42, 42, 42)
                .addComponent(reception)
                .addGap(50, 50, 50)
                .addComponent(statistiques)
                .addGap(37, 37, 37)
                .addComponent(chiffreAffaires)
                .addGap(38, 38, 38)
                .addComponent(personnel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(seconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout panebureauLayout = new javax.swing.GroupLayout(panebureau);
        panebureau.setLayout(panebureauLayout);
        panebureauLayout.setHorizontalGroup(
            panebureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        panebureauLayout.setVerticalGroup(
            panebureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_32.png"))); // NOI18N
        jMenu1.setText("ACCUEUIL");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fermer_32.png"))); // NOI18N
        jMenu3.setText("QUITTER");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panebureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panebureau))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptionMouseClicked
        // TODO add your handling code here:
         if(reception.isEnabled()){
        
         panebureau.removeAll();
        panebureau.repaint();//reafficher
        formreception fe=new formreception(); // creation d'un formeleves
        fe.setSize(panebureau.getSize().width, panebureau.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureau.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
    }//GEN-LAST:event_receptionMouseClicked

    private void expeditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expeditionMouseClicked
        // TODO add your handling code here:
         if(expedition.isEnabled()){
        
         panebureau.removeAll();
        panebureau.repaint();//reafficher
        renseignecolis fe=new renseignecolis(); // creation d'un formeleves
        fe.setSize(panebureau.getSize().width, panebureau.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureau.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
    }//GEN-LAST:event_expeditionMouseClicked

    private void statistiquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistiquesMouseClicked
        // TODO add your handling code here:
         if(statistiques.isEnabled()){
        
         panebureau.removeAll();
        panebureau.repaint();//reafficher
        Statistiquecolis fe=new Statistiquecolis(); // creation d'un formeleves
        fe.setSize(panebureau.getSize().width, panebureau.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureau.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
    }//GEN-LAST:event_statistiquesMouseClicked

    private void chiffreAffairesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chiffreAffairesMouseClicked
        // TODO add your handling code here:
         if(chiffreAffaires.isEnabled()){
        
         panebureau.removeAll();
        panebureau.repaint();//reafficher
        chiffres fe=new chiffres(); // creation d'un formeleves
        fe.setSize(panebureau.getSize().width, panebureau.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureau.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
    }//GEN-LAST:event_chiffreAffairesMouseClicked

    private void seconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seconnecterActionPerformed
        // TODO add your handling code here:
         if(seconnecter.isEnabled()){
        
         panebureau.removeAll();
        panebureau.repaint();//reafficher
        formconnexion fe=new formconnexion(); // creation d'un formeleves
        fe.setSize(panebureau.getSize().width, panebureau.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureau.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
         
         
         
        
    }//GEN-LAST:event_seconnecterActionPerformed

    private void personnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personnelMouseClicked
        // TODO add your handling code here:
          if(personnel.isEnabled()){
        
         panebureau.removeAll();
        panebureau.repaint();//reafficher
        Forminscrit fe=new Forminscrit(); // creation d'un formeleves
        fe.setSize(panebureau.getSize().width, panebureau.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureau.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
    }//GEN-LAST:event_personnelMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_jMenu3MouseClicked

    
    
    private void activerMenus(boolean chiffreAffaire, boolean profil, boolean expedition, boolean reception, boolean personnel, boolean statistique) {
    chiffreAffaires.setEnabled(chiffreAffaire);
    statistiques.setEnabled(profil);
    this.expedition.setEnabled(expedition);
    this.reception.setEnabled(reception);
    this.personnel.setEnabled(personnel);
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(colismain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(colismain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(colismain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(colismain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new colismain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel chiffreAffaires;
    public static javax.swing.JLabel expedition;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JDesktopPane panebureau;
    public static javax.swing.JLabel personnel;
    public static javax.swing.JLabel reception;
    public static javax.swing.JButton seconnecter;
    public static javax.swing.JLabel statistiques;
    // End of variables declaration//GEN-END:variables
}
