/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestcolis;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.*;
import java.sql.*;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;



/**
 *
 * @author kamke
 */
public class formutilisateur extends javax.swing.JPanel {

    
            
    /**
     * Creates new form formutilisateur
     */
    public formutilisateur() {
        initComponents();
        chargerGroupes();
    }

       private void enregistrerUtilisateur() throws NoSuchAlgorithmException {
    String nometprenom = txtnometprenom.getText();
    String nomutilisateur = txtnomutilisateur.getText();
    String password = new String(txtpassword.getPassword());
    String profil = (String) cmbprofil.getSelectedItem();
        
    if (nometprenom.isEmpty() || nomutilisateur.isEmpty() || password.isEmpty() || profil == null) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Chiffrer le mot de passe avant de l'enregistrer
    String hashedPassword = Utilitaire.hashPassword(password);  // Utiliser le mot de passe haché

    String sql = "INSERT INTO utilisateur (identifiant, password, utilisateur, groupe) VALUES (?, ?, ?, ?)";
    
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bdcolis", "root", "");
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        // Passer les valeurs à la requête SQL
        ps.setString(1, nometprenom);  // identifiant
        ps.setString(2, hashedPassword);  // Mot de passe haché
        ps.setString(3, nomutilisateur);  // Utilisateur
        ps.setString(4, profil);  // Groupe

        // Exécution de la requête
        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Utilisateur ajouté avec succès !");
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de l'utilisateur.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnometprenom = new javax.swing.JTextField();
        txtnomutilisateur = new javax.swing.JTextField();
        cmbprofil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnannuler = new javax.swing.JButton();
        btnquitter = new javax.swing.JButton();
        btnvalider = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        cmbprofil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbprofilFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom et Prenom");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Profil");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom d'utilisateur");

        btnannuler.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnannuler.setForeground(new java.awt.Color(0, 102, 102));
        btnannuler.setText("Annuler");

        btnquitter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnquitter.setForeground(new java.awt.Color(0, 102, 102));
        btnquitter.setText("Quitter");

        btnvalider.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnvalider.setForeground(new java.awt.Color(0, 102, 102));
        btnvalider.setText("Valider");
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(txtnometprenom))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbprofil, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnvalider))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomutilisateur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnannuler)
                                    .addGap(42, 42, 42)
                                    .addComponent(btnquitter))))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnometprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomutilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbprofil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnquitter)
                    .addComponent(btnannuler)
                    .addComponent(btnvalider))
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        try {
            // TODO add your handling code here:

            enregistrerUtilisateur();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(formutilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtnometprenom.setText("");
        txtnomutilisateur.setText("");
        txtpassword.setText("");
       
        
    }//GEN-LAST:event_btnvaliderActionPerformed

    
    
public class Utilitaire {

    // Méthode pour hacher le mot de passe avec SHA-256
    public static String hashPassword(String password) throws NoSuchAlgorithmException {
        // Créer un objet MessageDigest avec l'algorithme SHA-256
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        
        // Hacher le mot de passe
        byte[] encodedhash = digest.digest(password.getBytes());
        
        // Convertir en chaîne hexadécimale
        StringBuilder hexString = new StringBuilder();
        for (byte b : encodedhash) {
            hexString.append(String.format("%02x", b));
        }
        
        return hexString.toString();
    }
}


    private void cmbprofilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbprofilFocusGained
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_cmbprofilFocusGained

    private void chargerGroupes() {
    // Connexion à la base de données
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bdcolis", "root", "");
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT groupe FROM profil")) {

        // Vider le JComboBox avant de le remplir
        cmbprofil.removeAllItems();

        // Ajouter les groupes au JComboBox
        while (rs.next()) {
            String groupe = rs.getString("groupe");
            cmbprofil.addItem(groupe);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erreur lors du chargement des groupes : " + ex.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnannuler;
    private javax.swing.JButton btnquitter;
    private javax.swing.JButton btnvalider;
    private javax.swing.JComboBox<String> cmbprofil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtnometprenom;
    private javax.swing.JTextField txtnomutilisateur;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    void moveToFront() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
