/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gestcolis;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import   classe.connectionbd; // Pour la connexion à la base de données
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author HP
 */
public class formprofil extends javax.swing.JInternalFrame {
    
    private javax.swing.JButton btnEnregistrer;
    
    
    private void insererProfil() throws ClassNotFoundException {
        
        
        String groupe = txtgroupe.getText();
         boolean chiffreAffaire = chchif.isSelected();
         boolean profil = chpro.isSelected();
         boolean expedition = chexp.isSelected();
         boolean reception = chrec.isSelected();
         boolean personnel = chperso.isSelected();
         boolean statistique = chstat.isSelected();
    
         if (groupe.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Le champ 'Groupe' ne peut pas être vide.", "Erreur", JOptionPane.ERROR_MESSAGE);
                 return;
    }

    
         // Requête SQL pour insérer dans la table profil
         String sql = "INSERT INTO profil (groupe, chiffre_affaire, profil, expédition, réception, personnel, statistique) VALUES (?, ?, ?, ?, ?, ?, ?)";
    
         try (Connection con = classe.connectionbd.seconnecter(); 
         PreparedStatement ps = con.prepareStatement(sql)) {
        
             ps.setString(1, groupe);
             ps.setBoolean(2, chiffreAffaire);
             ps.setBoolean(3, profil);
             ps.setBoolean(4, expedition);
             ps.setBoolean(5, reception);
             ps.setBoolean(6, personnel);
             ps.setBoolean(7, statistique);
        
        // Exécution de la requête
        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Profil créé avec succès !");
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la création du profil.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erreur de connexion ou de requête SQL : " + ex.getMessage());
    }
}
    
        
    
    
    
    
    /**
     * Creates new form formprofil
     */
    public formprofil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        chchif = new javax.swing.JCheckBox();
        chpro = new javax.swing.JCheckBox();
        chexp = new javax.swing.JCheckBox();
        chstat = new javax.swing.JCheckBox();
        chrec = new javax.swing.JCheckBox();
        txtgroupe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnenregistrer = new javax.swing.JButton();
        chperso = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        chchif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chchif.setForeground(new java.awt.Color(0, 102, 102));
        chchif.setText("Chiffre d'affaire");
        chchif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chchifActionPerformed(evt);
            }
        });

        chpro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chpro.setForeground(new java.awt.Color(0, 102, 102));
        chpro.setText("Profil");

        chexp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chexp.setForeground(new java.awt.Color(0, 102, 102));
        chexp.setText("Expédition");

        chstat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chstat.setForeground(new java.awt.Color(0, 102, 102));
        chstat.setText("Statistique");

        chrec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chrec.setForeground(new java.awt.Color(0, 102, 102));
        chrec.setText("Réception");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Groupe");

        btnenregistrer.setText("Enregistrer");
        btnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregistrerActionPerformed(evt);
            }
        });

        chperso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chperso.setForeground(new java.awt.Color(0, 102, 102));
        chperso.setText("Personnel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chpro)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(chchif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chperso)
                                    .addComponent(chrec)
                                    .addComponent(chstat)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnenregistrer)
                            .addComponent(txtgroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chexp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtgroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chchif)
                    .addComponent(chstat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chpro)
                    .addComponent(chrec))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chexp)
                    .addComponent(chperso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnenregistrer)
                .addGap(92, 92, 92))
        );

        jTabbedPane1.addTab("Profil", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chchifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chchifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chchifActionPerformed

    private void btnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregistrerActionPerformed
        try {
            // TODO add your handling code here:
            
            insererProfil();
            txtgroupe.setText("");
            chchif.setSelected(false);
            chexp.setSelected(false);
            chperso.setSelected(false);
            chpro.setSelected(false);
            chrec.setSelected(false);
            chstat.setSelected(false);
            
            
            
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formprofil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnenregistrerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenregistrer;
    private javax.swing.JCheckBox chchif;
    private javax.swing.JCheckBox chexp;
    private javax.swing.JCheckBox chperso;
    private javax.swing.JCheckBox chpro;
    private javax.swing.JCheckBox chrec;
    private javax.swing.JCheckBox chstat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtgroupe;
    // End of variables declaration//GEN-END:variables
}
