/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestcolis;

import static gestcolis.colismain.panebureau;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author kamke
 */
public class Forminscrit extends javax.swing.JPanel {

    /**
     * Creates new form Forminscrit
     */
    public Forminscrit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        monprofil = new javax.swing.JLabel();
        monuser = new javax.swing.JLabel();
        panebureauperson = new javax.swing.JDesktopPane();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        monprofil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        monprofil.setForeground(new java.awt.Color(255, 255, 255));
        monprofil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nouvelpersonnel_32.png"))); // NOI18N
        monprofil.setText("Profil");
        monprofil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monprofilMouseClicked(evt);
            }
        });

        monuser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        monuser.setForeground(new java.awt.Color(255, 255, 255));
        monuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/utilisateur_32.png"))); // NOI18N
        monuser.setText("User");
        monuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monuserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monprofil)
                    .addComponent(monuser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(monprofil)
                .addGap(74, 74, 74)
                .addComponent(monuser)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panebureaupersonLayout = new javax.swing.GroupLayout(panebureauperson);
        panebureauperson.setLayout(panebureaupersonLayout);
        panebureaupersonLayout.setHorizontalGroup(
            panebureaupersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        panebureaupersonLayout.setVerticalGroup(
            panebureaupersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panebureauperson)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panebureauperson))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void monprofilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monprofilMouseClicked
        // TODO add your handling code here:
          if(monprofil.isEnabled()){
        
         panebureauperson.removeAll();
        panebureauperson.repaint();//reafficher
        formprofil fe=new formprofil(); // creation d'un formeleves
        fe.setSize(panebureauperson.getSize().width, panebureauperson.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureauperson.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
    }//GEN-LAST:event_monprofilMouseClicked

    private void monuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monuserMouseClicked
        // TODO add your handling code here:
        
          if(monuser.isEnabled()){
        
         panebureauperson.removeAll();
        panebureauperson.repaint();//reafficher
        formutilisateur fe=new formutilisateur(); // creation d'un formeleves
        fe.setSize(panebureauperson.getSize().width, panebureauperson.getSize().height);
        fe.setVisible(true);// pour le rendre visible
        panebureauperson.add(fe);// on l'ajoute dans la fen^tre panebureau
        fe.setLocation(0,0);
        fe.moveToFront();//pour le placer en avant
        }
        
    }//GEN-LAST:event_monuserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monprofil;
    private javax.swing.JLabel monuser;
    private javax.swing.JDesktopPane panebureauperson;
    // End of variables declaration//GEN-END:variables

    void moveToFront() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
