/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gestcolis;


import classe.colis;
import static gestcolis.Gestcolis.*;

import com.mysql.cj.xdevapi.Statement;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import java.util.HashMap;
import java.util.Map;
import java.sql.*;
import static java.time.Instant.now;


/**
 *
 * @author kamke
 */
public class renseignecolis extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public renseignecolis() {
        initComponents();
        initialiserQuartiers();
        initialiserType();
        initialiserPrix();
        modesulter();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomColis = new javax.swing.JTextField();
        txtNomexpedit = new javax.swing.JTextField();
        txtPrenomExpedit = new javax.swing.JTextField();
        cmbVilleExpedit = new javax.swing.JComboBox<>();
        txtTelephoneExpedit = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField12 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNomDestinataire = new javax.swing.JTextField();
        txtPrenomDestinataire = new javax.swing.JTextField();
        txtTelephoneDestinataire = new javax.swing.JTextField();
        cmbVilleDestinataire = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cmbQuartierDestinataire = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        btnNouveau = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtFraisEnvoi = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnValider = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        dtDateEnvoi = new com.toedter.calendar.JDateChooser();
        txtCodeEnvoi = new javax.swing.JTextField();
        Cmbpoids = new javax.swing.JComboBox<>();
        Cmbtype = new javax.swing.JComboBox<>();
        btnimprimer = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("description");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Expéditeur :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prénom(s)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Téléphone");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Colis :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Poids");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ville");

        txtPrenomExpedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomExpeditActionPerformed(evt);
            }
        });

        cmbVilleExpedit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOBO-DIOULASSO", "OUAGADOUGOU", "KOUDOUGOU", "BANFORA", "DORIS", "OUAYGOUYA" }));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nom du colis");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Type");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Expediteur :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nom");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Prenom");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Téléphone");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Colis :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Poids");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ville");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel19)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Destinataire :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nom");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Prénom(s)");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Ville");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Téléphone");

        cmbVilleDestinataire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUAGADOUGOU", "KOUDOUGOU", "BANFORA", "DORI", "OUAHIGOUYA", " " }));
        cmbVilleDestinataire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVilleDestinataireActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Quartier ");

        cmbQuartierDestinataire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOUNGUIN", "KARPALA", "GNONSAIN", "TAMPUI", "TAMGUIN", "OUAGA-2000", "BONHEUR-VILLE", "PETIT-PARIS", "ZONE 1", "ZONZ 2" }));
        cmbQuartierDestinataire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuartierDestinataireActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Date d'envoi");

        btnNouveau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNouveau.setForeground(new java.awt.Color(0, 102, 102));
        btnNouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/actualiser_32.png"))); // NOI18N
        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Frais d'envoi");

        txtFraisEnvoi.setEnabled(false);
        txtFraisEnvoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraisEnvoiActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Code d'envoi");

        btnValider.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnValider.setForeground(new java.awt.Color(102, 0, 0));
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/valider_32.png"))); // NOI18N
        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnQuitter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fermer_32.png"))); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        dtDateEnvoi.setForeground(new java.awt.Color(153, 255, 102));
        dtDateEnvoi.setDateFormatString("dd/MM/yyyy");

        txtCodeEnvoi.setEnabled(false);
        txtCodeEnvoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeEnvoiActionPerformed(evt);
            }
        });

        Cmbpoids.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1kg-25kg", "25kg-40kg", "40kg-60kg", "60kg-100kg", "100kg - ++kg" }));
        Cmbpoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbpoidsActionPerformed(evt);
            }
        });

        Cmbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leger", "Lourd" }));
        Cmbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbtypeActionPerformed(evt);
            }
        });

        btnimprimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnimprimer.setForeground(new java.awt.Color(0, 102, 102));
        btnimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel_32.png"))); // NOI18N
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomColis, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31)
                        .addComponent(Cmbpoids, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomexpedit))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbVilleExpedit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrenomExpedit, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(txtTelephoneExpedit)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrenomDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnimprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbQuartierDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbVilleDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFraisEnvoi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTelephoneDestinataire))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtDateEnvoi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(txtCodeEnvoi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(jLabel27)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 360, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 361, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtNomColis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Cmbpoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtNomexpedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrenomExpedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtTelephoneExpedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cmbVilleExpedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(txtPrenomDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomDestinataire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txtTelephoneDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVilleDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbQuartierDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addComponent(dtDateEnvoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFraisEnvoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodeEnvoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNouveau)
                    .addComponent(btnValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimer))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 241, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 242, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrenomExpeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomExpeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomExpeditActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        // TODO add your handling code here:
         String prefixe = "B";
    int numeroAleatoire = (int) (Math.random() * 100000000); // Générer un numéro entre 0 et 999999
    String codeEnvoi = prefixe + String.format("%08d", numeroAleatoire); // Assurer que le numéro a 6 chiffres

    // Afficher le code dans le champ texte
    txtCodeEnvoi.setText(codeEnvoi);
     // Réinitialiser les champs texte
    txtNomColis.setText("");
    Cmbpoids.setSelectedItem("");
    Cmbtype.setSelectedItem("");
    txtNomexpedit.setText("");
    txtPrenomExpedit.setText("");
    txtTelephoneExpedit.setText("");
    txtNomDestinataire.setText("");
    txtPrenomDestinataire.setText("");
    txtTelephoneDestinataire.setText("");
    txtFraisEnvoi.setText("");
    

    // Réinitialiser les JComboBox (sélectionner le premier élément par défaut)
    cmbVilleExpedit.setSelectedIndex(0);
    cmbVilleDestinataire.setSelectedIndex(0);
    cmbQuartierDestinataire.setSelectedIndex(0);

    // Réinitialiser le JDateChooser avec la date du jour
     
//    dtDateEnvoi.setDate(new Date());
    
   

         btnNouveau.setEnabled(false);  // Désactiver le bouton "Nouveau"
        btnimprimer.setEnabled(false); // Désactiver le bouton "Imprimer"
      btnValider.setEnabled(true);
        modeactver();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
      try {
        // Récupération des données des champs, avec vérifications de base
        String nomcolis = txtNomColis.getText().trim();
        String type = (Cmbtype.getSelectedItem() != null) ? Cmbtype.getSelectedItem().toString() : "";
        
        Object selectedPoids = Cmbpoids.getSelectedItem();
        if (selectedPoids == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un poids.", "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String poids = selectedPoids.toString();
        
        String nomexpediteur = txtNomexpedit.getText().trim();
        String prenomexpediteur = txtPrenomExpedit.getText().trim();
        String telephoneexpediteur = txtTelephoneExpedit.getText().trim();
        String villeexpediteur = (cmbVilleExpedit.getSelectedItem() != null) ? cmbVilleExpedit.getSelectedItem().toString() : "";
        
        String nomdestinataire = txtNomDestinataire.getText().trim();
        String prenomdestinataire = txtPrenomDestinataire.getText().trim();
        String telephonedestinataire = txtTelephoneDestinataire.getText().trim();
        String villedestinataire = (cmbVilleDestinataire.getSelectedItem() != null) ? cmbVilleDestinataire.getSelectedItem().toString() : "";
        String quartierdestinataire = (cmbQuartierDestinataire.getSelectedItem() != null) ? cmbQuartierDestinataire.getSelectedItem().toString() : "";
        
        String codeenvoi = txtCodeEnvoi.getText().trim();
        
        // Vérification des champs obligatoires
        if (nomcolis.isEmpty() || type.isEmpty() || poids.isEmpty() || nomexpediteur.isEmpty() ||
            prenomexpediteur.isEmpty() || telephoneexpediteur.isEmpty() || villeexpediteur.isEmpty() ||
            nomdestinataire.isEmpty() || prenomdestinataire.isEmpty() || telephonedestinataire.isEmpty() ||
            villedestinataire.isEmpty() || codeenvoi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.", "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Vérification et formatage de la date d'envoi au format "yyyy-MM-dd"
        SimpleDateFormat fd = new SimpleDateFormat("yyyy-MM-dd");
        if (dtDateEnvoi.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une date d'envoi.", "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateenvoi = sdf.format(new Date());

      //  String dateEnvoi = fd.format(dtDateEnvoi.getDate());
        
        // Vérification du prix associé à la plage de poids (assurez-vous que la HashMap poidsParPrix est initialisée)
        if (!poidsParPrix.containsKey(poids)) {
            JOptionPane.showMessageDialog(this, "Erreur : Prix introuvable pour la plage de poids sélectionnée.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fraisenvoi = poidsParPrix.get(poids).toString();
        
        // Appel de la méthode enregistrer qui effectue l'insertion dans les tables appropriées
     colis.enregistrerColis(nomcolis, type, poids, nomexpediteur, prenomexpediteur, telephoneexpediteur, villeexpediteur, fraisenvoi, codeenvoi, nomdestinataire, prenomdestinataire, telephonedestinataire, villedestinataire, quartierdestinataire, dateenvoi);
      
      } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Une erreur est survenue : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        // Afficher un message de confirmation
//        JOptionPane.showMessageDialog(this, "Enregistrement réussi !", "Succès", JOptionPane.INFORMATION_MESSAGE);



    }

       btnValider.setEnabled(false);
        btnNouveau.setEnabled(false);
        btnimprimer.setEnabled(true);
      
    }//GEN-LAST:event_btnValiderActionPerformed
    private Map<String, String[]> quartiersParVille;

private void initialiserQuartiers() {
    quartiersParVille = new HashMap<>();
    quartiersParVille.put("OUAGADOUGOU", new String[]{"Goughin", "Tampouy", "Zone 1", "Karpala", "Centre-Ville"});
    quartiersParVille.put("KOUDOUGOU", new String[]{"Pella", "Poa", "Koudougou", "Nondiala", "Bingo", "Reo"});
    quartiersParVille.put("BANFORA", new String[]{"Secteur 1", "Secteur 2", "Secteur 3", "Secteur 4", "Secteur 5", "Secteur 6"});
    quartiersParVille.put("DORI", new String[]{"Secteur 6", "Secteur 7", "Secteur 8"});
    quartiersParVille.put("OUAHIGOUYA", new String[]{"Secteur 6", "Secteur 7", "Secteur 8"});
}
   private Map<String, String[]> TypeparPoids;

private void initialiserType() {
    // Déclaration correcte de la HashMap
    TypeparPoids = new HashMap<>();

    // Association des types aux plages de poids
    TypeparPoids.put("Leger", new String[]{"1kg-25kg"});
    TypeparPoids.put("Lourd", new String[]{"25kg-40kg", "40kg-60kg", "60kg-100kg", "100kg - ++kg"});
}
    private Map<String, Integer> poidsParPrix;
    
    private void modesulter()
    {
        txtNomColis.setEnabled(false);
        txtNomDestinataire.setEnabled(false);
        txtNomexpedit.setEnabled(false);
        txtPrenomDestinataire.setEnabled(false);
        txtPrenomExpedit.setEnabled(false);
        txtTelephoneDestinataire.setEnabled(false);
        txtTelephoneExpedit.setEnabled(false);
        dtDateEnvoi.setEnabled(false);
        
        cmbQuartierDestinataire.setEnabled(false);
        cmbVilleDestinataire.setEnabled(false);
        cmbVilleExpedit.setEnabled(false);
        Cmbtype.setEnabled(false);
        Cmbpoids.setEnabled(false);
        btnNouveau.setEnabled(true);
        btnQuitter.setEnabled(true);
        btnValider.setEnabled(false);
        btnimprimer.setEnabled(false);
    }
    
     private void modeactver()
    {
        txtNomColis.setEnabled(true);
        txtNomDestinataire.setEnabled(true);
        txtNomexpedit.setEnabled(true);
        txtPrenomDestinataire.setEnabled(true);
        txtPrenomExpedit.setEnabled(true);
        txtTelephoneDestinataire.setEnabled(true);
        txtTelephoneExpedit.setEnabled(true);
        dtDateEnvoi.setEnabled(true);
        
        cmbQuartierDestinataire.setEnabled(true);
        cmbVilleDestinataire.setEnabled(true);
        cmbVilleExpedit.setEnabled(true);
        Cmbtype.setEnabled(true);
        Cmbpoids.setEnabled(true);
       
    }

private void initialiserPrix() {
    // Associer chaque plage de poids à un prix
    poidsParPrix = new HashMap<>();
    poidsParPrix.put("1kg-25kg", 2000);
    poidsParPrix.put("25kg-40kg", 4000);
    poidsParPrix.put("40kg-60kg", 6000);
    poidsParPrix.put("60kg-100kg", 10000);
    poidsParPrix.put("100kg-++kg", 15000);
}


    
    private void cmbVilleDestinataireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVilleDestinataireActionPerformed
        // TODO add your handling code here:
        // Récupérer la ville sélectionnée
    String ville = cmbVilleDestinataire.getSelectedItem().toString();

    // Mettre à jour les quartiers en fonction de la ville
    String[] quartiers = quartiersParVille.get(ville);
    if (quartiers != null) {
        cmbQuartierDestinataire.removeAllItems(); // Vider les options existantes
        for (String quartier : quartiers) {
            cmbQuartierDestinataire.addItem(quartier); // Ajouter les nouveaux quartiers
        }
    } else {
        cmbQuartierDestinataire.removeAllItems(); // Si la ville n'est pas définie, vider les quartiers
    }

    }//GEN-LAST:event_cmbVilleDestinataireActionPerformed

    private void cmbQuartierDestinataireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuartierDestinataireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbQuartierDestinataireActionPerformed

    private void CmbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbtypeActionPerformed
        // TODO add your handling code here:
    String type = Cmbtype.getSelectedItem().toString(); // Récupérer le type sélectionné
    
    // Récupérer les poids associés au type de colis
    String[] poids = TypeparPoids.get(type);
    
    if (poids != null) {
        Cmbpoids.removeAllItems(); // Vider les options existantes
        
        for (String p : poids) { // Ajouter chaque plage de poids au ComboBox
            Cmbpoids.addItem(p); 
        }
    } else {
        Cmbpoids.removeAllItems(); // Si le type n'existe pas, vider les options
    }

    }//GEN-LAST:event_CmbtypeActionPerformed

    private void txtFraisEnvoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraisEnvoiActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtFraisEnvoiActionPerformed

    private void CmbpoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbpoidsActionPerformed
        // TODO add your handling code here:
        // Récupérer la plage de poids sélectionnée
    String poids = Cmbpoids.getSelectedItem().toString();

    // Récupérer le prix associé à la plage de poids
    Integer prix = poidsParPrix.get(poids);
    if (prix != null) {
        txtFraisEnvoi.setText(prix + " F"); // Mettre à jour le champ du prix
    } else {
        txtFraisEnvoi.setText(""); // Vider le champ si aucun prix n'est trouvé
    }
    }//GEN-LAST:event_CmbpoidsActionPerformed

    private void txtCodeEnvoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeEnvoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeEnvoiActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
        
        int choix = JOptionPane.showConfirmDialog(this, 
        "Êtes-vous sûr de vouloir vouloir retourner au menu ?", 
        "Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);
    
    // Vérifier le choix de l'utilisateur
    if (choix == JOptionPane.YES_OPTION) {
        this.dispose(); // Fermer l'application
    }

    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(null, "Impression en cours...", "Impression", JOptionPane.INFORMATION_MESSAGE);
          
          modesulter();
          
    }//GEN-LAST:event_btnimprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmbpoids;
    private javax.swing.JComboBox<String> Cmbtype;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnValider;
    private javax.swing.JButton btnimprimer;
    private javax.swing.JComboBox<String> cmbQuartierDestinataire;
    private javax.swing.JComboBox<String> cmbVilleDestinataire;
    private javax.swing.JComboBox<String> cmbVilleExpedit;
    private com.toedter.calendar.JDateChooser dtDateEnvoi;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtCodeEnvoi;
    private javax.swing.JTextField txtFraisEnvoi;
    private javax.swing.JTextField txtNomColis;
    private javax.swing.JTextField txtNomDestinataire;
    private javax.swing.JTextField txtNomexpedit;
    private javax.swing.JTextField txtPrenomDestinataire;
    private javax.swing.JTextField txtPrenomExpedit;
    private javax.swing.JTextField txtTelephoneDestinataire;
    private javax.swing.JTextField txtTelephoneExpedit;
    // End of variables declaration//GEN-END:variables

    private void enregistrer(String codeenvoi, String nomcolis, String type, String poids, String nomexpediteur, String prenomexpediteur, String telephoneexpediteur, String villeexpediteur, String nomdestinataire, String prenomdestinataire, String telephonedestinataire, String villedestinataire, String quartierdestinataire, String fraisenvoi, String dateEnvoi) {
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
